# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        CoreBundle\Entity\Clientes:
            algorithm: plaintext

        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

        user_db:
            entity: { class: CoreBundle\Entity\Clientes }
            #entity: { class: Acme\UserBundle\Entity\User, property: username }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_admin:
            anonymous: ~
            pattern:    ^/admin/.*
            provider: in_memory
            logout:
                path:   /admin/logout
                target: adminlogin
            form_login:
                login_path: adminlogin
                check_path: adminlogin
                default_target_path: admin_home
                always_use_default_target_path: true
                target_path_parameter: admin_home
        #    context: uumweb

        main:
            anonymous: ~
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
                username_parameter: login[email]
                password_parameter: login[password]
                csrf_parameter: login[_token]
                success_handler: frontend.component.authentication.handler.login_success_handler
            provider: user_db
            logout:
                path:   /logout
                target: login
                success_handler: frontend.component.authentication.handler.logout_success_handler
         #   context: uumweb
            # activate different ways to authenticate
    #    secured_area:
            # ...
    #        pattern: ^/
    #        provider: user_db
    #        form_login: ~
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activar, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/webkcon, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pagos/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/boletin, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pago/.*, role: ROLE_USER }
        - { path: ^/contenido/.*, role: ROLE_USER }
        - { path: ^/norma/.*, role: ROLE_USER }
        - { path: ^/gestion/.*, role: ROLE_USER }
        - { path: ^/pedido/.*, role: ROLE_USER }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/.*, role: ROLE_ADMIN }
